### ISSUE TITLE
How to access sextant application?

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-sextant#1]
http://tomcat_host:8080/Sextant_v2.0 does not work (404)

**Comment by gpapadis** [comment]
Hi Ivan, 
did you run the application as specified here: https://github.com/big-data-europe/README/wiki/Sextant?

**Comment by earthquakesan** [comment]
Ah, was configuration mistake, sorry.

Can you please include docker-compose.yml snippet to wiki/README.md file?

```
version: '2'
services:
  sextant:
    image: bde2020/sextant
    hostname: sextant 
    ports:
      - "8080:8080"
```
